books:
  - name: "Platform FAQ"
    pages:
      - name: "Platform FAQ for B2B Operators"
        link: "https://book.gambchamp.com/books/platform-faq/page/platform-faq-for-b2b-operators"
  - name: "Game Hub"
    pages:
      - name: "Creating and Editing a Game"
        link: "https://book.gambchamp.com/books/game-management/page/creating-and-editing-a-game"
  - name: "Project Settings"
    pages:
      - name: "GEO Management. BackOffice"
        link: "https://book.gambchamp.com/books/project-settings/page/geo-management-backoffice"
  - name: "Bonuses and Promo"
    pages:
      - name: "Batch Templates. BackOffice"
        link: "https://book.gambchamp.com/books/bonuses-and-promo/page/batch-templates-backoffice"
      - name: "Creating and editing an info card"
        link: "https://book.gambchamp.com/books/bonuses-and-promo/page/creating-and-editing-an-info-card"
      - name: "Wagering Contribution Rules. BackOffice"
        link: "https://book.gambchamp.com/books/bonuses-and-promo/page/wagering-contribution-rules-backoffice"
      - name: "Creating and Editing a Wagering Contribution Rule"
        link: "https://book.gambchamp.com/books/bonuses-and-promo/page/creating-and-editing-a-wagering-contribution-rule"
  - name: "Notification System"
    pages:
      - name: "Email Templates. BackOffice"
        link: "https://book.gambchamp.com/books/notification-system/page/email-templates-backoffice"
      - name: "List of JSON variables in email templates"
        link: "https://book.gambchamp.com/books/notification-system/page/list-of-json-variables-in-email-templates"
  - name: "Payment Systems"
    pages:
      - name: "Transactions. BackOffice"
        link: "https://book.gambchamp.com/books/payment-systems/page/transactions-backoffice"
      - name: "Deposit Wager. BackOffice"
        link: "https://book.gambchamp.com/books/payment-systems/page/deposit-wager-backoffice"
      - name: "Fast Deposit. BackOffice"
        link: "https://book.gambchamp.com/books/payment-systems/page/fast-deposit-backoffice"
      - name: "Creating and editing a deposit wager rule"
        link: "https://book.gambchamp.com/books/payment-systems/page/creating-and-editing-a-deposit-wager-rule"
      - name: "Payment Systems (new). BackOffice"
        link: "https://book.gambchamp.com/books/payment-systems/page/payment-systems-new-backoffice"
      - name: "Editing a payment system"
        link: "https://book.gambchamp.com/books/payment-systems/page/editing-a-payment-system"
      - name: "Withdrawal Limits. BackOffice"
        link: "https://book.gambchamp.com/books/payment-systems/page/withdrawal-limits-backoffice"
      - name: "Creating and Editing a Withdrawal Limit"
        link: "https://book.gambchamp.com/books/payment-systems/page/creating-and-editing-a-withdrawal-limit"
  - name: "Smartico Integration"
    pages:
      - name: "Configuring Webhooks in the Smartico BackOffice"
        link: "https://book.gambchamp.com/books/smartico-integration/page/configuring-webhooks-in-the-smartico-backoffice"
  - name: "Content Management"
    pages:
      - name: "Help Center Settings. BackOffice"
        link: "https://book.gambchamp.com/books/content-management/page/help-center-settings-backoffice"
      - name: "Main Screen. BackOffice"
        link: "https://book.gambchamp.com/books/content-management/page/main-screen-backoffice"
      - name: "Payment Methods. BackOffice"
        link: "https://book.gambchamp.com/books/content-management/page/payment-methods-backoffice"
      - name: "Payment Stickers. BackOffice"
        link: "https://book.gambchamp.com/books/content-management/page/payment-stickers-backoffice"
  - name: "Analytics"
    pages:
      - name: "PowerBI Reports. BackOffice"
        link: "https://book.gambchamp.com/books/analytics/page/powerbi-reports-backoffice"
  - name: "Amplitude Integration"
    pages:
      - name: "Events for Amplitude"
        link: "https://book.gambchamp.com/books/amplitude-integration/page/events-for-amplitude"
  - name: "Platform Settings"
    pages:
      - name: "Interface Language. BackOffice"
        link: "https://book.gambchamp.com/books/platform-settings/page/interface-language-backoffice"
      - name: "Admin Management. BackOffice"
        link: "https://book.gambchamp.com/books/platform-settings/page/admin-management-backoffice"
      - name: "Creating and Editing an Administrator"
        link: "https://book.gambchamp.com/books/platform-settings/page/creating-and-editing-an-administrator"
      - name: "Administrator Rights"
        link: "https://book.gambchamp.com/books/platform-settings/page/administrator-rights"
  - name: "Intercom Integration"
    pages:
      - name: "Data in Intercom"
        link: "https://book.gambchamp.com/books/intercom-integration/page/data-in-intercom"
  - name: "Platform Mechanics"
    pages:
      - name: "Balances"
        link: "https://book.gambchamp.com/books/platform-mechanics/page/balances"
      - name: "Jackpots"
        link: "https://book.gambchamp.com/books/platform-mechanics/page/jackpots"
      - name: "Deposit Wager"
        link: "https://book.gambchamp.com/books/platform-mechanics/page/deposit-wager"
      - name: "User's Language"
        link: "https://book.gambchamp.com/books/platform-mechanics/page/users-language"
      - name: "Notification Triggers"
        link: "https://book.gambchamp.com/books/platform-mechanics/page/notification-triggers"
      - name: "Withdrawal Limits"
        link: "https://book.gambchamp.com/books/platform-mechanics/page/withdrawal-limits"
  - name: "BackOffice"
    pages:
      - name: "BackOffice"
        link: "https://book.gambchamp.com/books/backoffice/page/backoffice"
  - name: "Player Interface"
    pages:
      - name: "Fast Deposit"
        link: "https://book.gambchamp.com/books/player-interface/page/fast-deposit"
      - name: "Player Profile. Profile Data"
        link: "https://book.gambchamp.com/books/player-interface/page/player-profile-profile-data"
  - name: "PostHog Integration"
    pages:
      - name: "Data in PostHog"
        link: "https://book.gambchamp.com/books/posthog-integration/page/data-in-posthog"
      - name: "Analysis of User Search Queries"
        link: "https://book.gambchamp.com/books/posthog-integration/page/analysis-of-user-search-queries"
  - name: "Game Aggregator Integration"
    pages:
      - name: "Jackpot campaign list"
        link: "https://book.gambchamp.com/books/game-aggregator-integration/page/jackpot-campaign-list"
      - name: "Creating and editing a jackpot campaign"
        link: "https://book.gambchamp.com/books/game-aggregator-integration/page/creating-and-editing-a-jackpot-campaign"
  - name: "Users"
    pages:
      - name: "Campaign Details. Conditions"
        link: "https://book.gambchamp.com/books/users/page/campaign-details-conditions"
      - name: "Batch Details. Bonus types"
        link: "https://book.gambchamp.com/books/users/page/batch-details-bonus-types"

  # Release Notes
  - name: "Release Notes"
    pages:
      - name: "Release Notes v.27 – March 30, 2026"
        link: "https://book.gambchamp.com/books/release-notes/page/release-notes-v27-march-30-2026"
      - name: "Release Notes v.27.1 – April 1, 2026"
        link: "https://book.gambchamp.com/books/release-notes/page/release-notes-v271-april-1-2026"
      - name: "Release Notes v.28 – April 15, 2026"
        link: "https://book.gambchamp.com/books/release-notes/page/release-notes-v28-april-15-2026"
      - name: "Release Notes v.29 – April 22, 2026"
        link: "https://book.gambchamp.com/books/release-notes/page/release-notes-v29-april-22-2026"
